server:
  port: 8001
  servlet:
    context-path: /member

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml # 实现mapper接口配置见mapper和接口的绑定

spring:
  application:
    name: member # 设置应用程序的名称为 'member'
  profiles:
    active: dev  # 设置默认激活的配置文件
  main:
    allow-circular-references: true  # 允许循环引用
  datasource:
    driver-class-name: ${member.datasource.driver-class-name}
    url: jdbc:mysql://${member.datasource.host}:${member.datasource.port}/${member.datasource.database}
    username: ${member.datasource.username}
    password: ${member.datasource.password}




